/**
 * Demo dataset used when the real PSN scraper can't run (e.g. Bolt sandbox
 * blocked by PSN's CDN). Lets the user explore the panel end-to-end.
 */
import type { Game } from "./store";

const DEMO: Array<Omit<Game, "firstSeenAt" | "lastSeenAt" | "updatedAt" | "youtubeUrl">> = [
  {
    id: "UP9000-CUSA07408_00-REDEMPTION2000000",
    name: "Red Dead Redemption 2",
    imageUrl:
      "https://image.api.playstation.com/vulcan/ap/rnd/202010/2618/hjrIUe3GafRjUXKm2yQGcbpc.png",
    storeUrl:
      "https://store.playstation.com/en-us/product/UP9000-CUSA07408_00-REDEMPTION2000000",
    platforms: "PS4",
    priceOriginalCents: 5999,
    priceDiscountedCents: 1799,
    discountPercent: 70,
    discountEndAt: null,
    selected: false,
    published: false,
    notes: "",
    active: true,
  },
  {
    id: "UP1004-CUSA28005_00-EAGAMESFIFA23000",
    name: "EA SPORTS FC 24 Standard Edition",
    imageUrl:
      "https://image.api.playstation.com/vulcan/ap/rnd/202307/1308/8c0a8c20e0db3a8a8b6d9f8e8a7b0b0d.png",
    storeUrl: "https://store.playstation.com/en-us/product/UP1004-CUSA28005_00",
    platforms: "PS5,PS4",
    priceOriginalCents: 6999,
    priceDiscountedCents: 2099,
    discountPercent: 70,
    discountEndAt: null,
    selected: true,
    published: false,
    notes: "Muy pedido",
    active: true,
  },
  {
    id: "UP0002-CUSA15208_00-ASSASSINSCREEDOD",
    name: "Assassin's Creed Odyssey - Ultimate Edition",
    imageUrl:
      "https://image.api.playstation.com/vulcan/ap/rnd/202010/0222/Us50lSU9sZ6EU6JF0pBwSEaa.png",
    storeUrl:
      "https://store.playstation.com/en-us/product/UP0002-CUSA15208_00-ASSASSINSCREEDOD",
    platforms: "PS4",
    priceOriginalCents: 9999,
    priceDiscountedCents: 1499,
    discountPercent: 85,
    discountEndAt: null,
    selected: false,
    published: false,
    notes: "",
    active: true,
  },
  {
    id: "UP0002-CUSA07708_00-FARCRY5000000000",
    name: "Far Cry 5 Gold Edition",
    imageUrl:
      "https://image.api.playstation.com/vulcan/img/rnd/202010/2814/K18tWlAZgZRJOIrH2gCQqLc2.png",
    storeUrl: "https://store.playstation.com/en-us/product/UP0002-CUSA07708_00",
    platforms: "PS4",
    priceOriginalCents: 4999,
    priceDiscountedCents: 999,
    discountPercent: 80,
    discountEndAt: null,
    selected: false,
    published: false,
    notes: "",
    active: true,
  },
  {
    id: "UP0082-CUSA10612_00-0000000000DMC5SE",
    name: "Devil May Cry 5 Special Edition",
    imageUrl:
      "https://image.api.playstation.com/vulcan/ap/rnd/202008/1418/5fxYjzH3OYUz8oKm6nNBj2zi.png",
    storeUrl: "https://store.playstation.com/en-us/product/UP0082-CUSA10612_00",
    platforms: "PS5",
    priceOriginalCents: 3999,
    priceDiscountedCents: 1199,
    discountPercent: 70,
    discountEndAt: null,
    selected: false,
    published: false,
    notes: "",
    active: true,
  },
  {
    id: "UP9000-PPSA01325_00-GHOSTSDCPS5000000",
    name: "Ghost of Tsushima Director's Cut",
    imageUrl:
      "https://image.api.playstation.com/vulcan/ap/rnd/202107/3100/HO8vkO9pfRhy3ZM3XkR3KChM.png",
    storeUrl: "https://store.playstation.com/en-us/product/UP9000-PPSA01325_00",
    platforms: "PS5",
    priceOriginalCents: 6999,
    priceDiscountedCents: 3499,
    discountPercent: 50,
    discountEndAt: null,
    selected: false,
    published: false,
    notes: "",
    active: true,
  },
  {
    id: "UP1001-CUSA00900_00-THEWITCHER3WIDCR",
    name: "The Witcher 3: Wild Hunt - Complete Edition",
    imageUrl:
      "https://image.api.playstation.com/vulcan/ap/rnd/202112/1317/TO1ZKplpLwAgj7d7X4UwOqUL.png",
    storeUrl: "https://store.playstation.com/en-us/product/UP1001-CUSA00900_00",
    platforms: "PS5,PS4",
    priceOriginalCents: 4999,
    priceDiscountedCents: 999,
    discountPercent: 80,
    discountEndAt: null,
    selected: true,
    published: false,
    notes: "",
    active: true,
  },
  {
    id: "UP0082-PPSA01589_00-0000000000000RE4",
    name: "Resident Evil 4",
    imageUrl:
      "https://image.api.playstation.com/vulcan/ap/rnd/202210/2005/QyPrNQjzX7L3GekEhWn2y8rl.png",
    storeUrl: "https://store.playstation.com/en-us/product/UP0082-PPSA01589_00",
    platforms: "PS5,PS4",
    priceOriginalCents: 5999,
    priceDiscountedCents: 2999,
    discountPercent: 50,
    discountEndAt: null,
    selected: false,
    published: false,
    notes: "",
    active: true,
  },
  {
    id: "UP1018-CUSA05624_00-MARVELSSPIDERMAN",
    name: "Marvel's Spider-Man: Miles Morales",
    imageUrl:
      "https://image.api.playstation.com/vulcan/ap/rnd/202009/2921/cKnwVxfzfUW5gGGrtxnkjbVq.png",
    storeUrl: "https://store.playstation.com/en-us/product/UP1018-CUSA05624_00",
    platforms: "PS5,PS4",
    priceOriginalCents: 4999,
    priceDiscountedCents: 1999,
    discountPercent: 60,
    discountEndAt: null,
    selected: false,
    published: false,
    notes: "",
    active: true,
  },
  {
    id: "UP0001-CUSA11993_00-FORHONORMARCHING",
    name: "For Honor Marching Fire Edition",
    imageUrl:
      "https://image.api.playstation.com/vulcan/ap/rnd/202010/0222/OxSu7SWEa4rmQL1z7C5UscM5.png",
    storeUrl: "https://store.playstation.com/en-us/product/UP0001-CUSA11993_00",
    platforms: "PS4",
    priceOriginalCents: 5999,
    priceDiscountedCents: 899,
    discountPercent: 85,
    discountEndAt: null,
    selected: false,
    published: false,
    notes: "",
    active: true,
  },
];

export function demoGames(nowIso: string): Game[] {
  return DEMO.map((g) => ({
    ...g,
    youtubeUrl: "",
    firstSeenAt: nowIso,
    lastSeenAt: nowIso,
    updatedAt: nowIso,
  }));
}
